apiVersion: batch/v1
kind: Job
metadata:
  name: blogging-website-job
spec:
  template:
    spec:
      containers:
      - name: blogging-website-job
        image: yash5090/blogging-website:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
