apiVersion: v1
kind: Service
metadata:
  name: blogging-website-service
spec:
  selector:
    app: blogging-website
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
