apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogging-website-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: blogging-website
  template:
    metadata:
      labels:
        app: blogging-website
    spec:
      containers:
        - name: blogging-website
          image: yash5090/blogging-website:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
